export const positions = [
  {
    id: 'senior-designer',
    title: 'Senior Product Designer',
    team: 'Design',
    location: 'Москва / Remote',
    type: 'Full-time',
    salary: '250 000 – 400 000 ₽',
    experience: '5+ лет',
    short: 'Ведущий дизайнер продуктовых проектов. UX, UI, дизайн-системы.',
    description: 'Возьмёте на себя 2-3 ключевых продуктовых проекта. Ведёте дискавери, работаете с исследованиями, собираете дизайн-систему, защищаете решения перед клиентом.',
    responsibilities: [
      'Продуктовый дизайн: от исследований до готовых макетов',
      'Дизайн-системы и компонентные библиотеки',
      'Защита решений перед клиентом (call, презентации)',
      'Менторство junior-дизайнеров',
    ],
    requirements: [
      '5+ лет в продуктовом дизайне',
      'Сильный UI и ощущение интерфейсов',
      'Опыт с дизайн-системами (Figma, tokens)',
      'Английский B2+',
    ],
    benefits: [
      'ДМС со стоматологией',
      'Гибкий график или удалёнка',
      'Образовательный бюджет 100k ₽/год',
      'Корпоративный MacBook',
    ],
  },
  {
    id: 'senior-frontend',
    title: 'Senior Frontend Developer',
    team: 'Engineering',
    location: 'Москва / Remote',
    type: 'Full-time',
    salary: '300 000 – 450 000 ₽',
    experience: '5+ лет',
    short: 'Next.js, TypeScript, анимации, перфоманс. Придётся делать красиво и быстро.',
    description: 'Вы будете делать front-end на клиентских проектах — от лендингов до веб-приложений. Важен вкус, внимание к деталям и умение договариваться с дизайном.',
    responsibilities: [
      'Разработка на Next.js 15+ / React 19',
      'Сложные анимации (Framer Motion, GSAP)',
      'Архитектура и оптимизация',
      'Code review и менторство',
    ],
    requirements: [
      '5+ лет в frontend',
      'Глубокий TypeScript',
      'Опыт с анимациями, WebGL плюс',
      'Умение сдавать дедлайны',
    ],
    benefits: [
      'ДМС',
      'Удалёнка из любой точки',
      'Корпоративный ноутбук',
      'Образовательный бюджет',
    ],
  },
  {
    id: 'motion-designer',
    title: 'Motion Designer',
    team: 'Design',
    location: 'Remote',
    type: 'Contract',
    salary: '150 000 – 250 000 ₽ / проект',
    experience: '3+ года',
    short: 'After Effects, Rive, Lottie. Придавайте движение нашим интерфейсам.',
    description: 'Контрактная роль — привлекаем на конкретные проекты с motion-частью. Работа в Figma, After Effects, Rive, экспорт в Lottie.',
    responsibilities: [
      'Дизайн motion-концепций',
      'Реализация в AE / Rive',
      'Экспорт для веба (Lottie, WebM)',
      'Коммуникация с frontend',
    ],
    requirements: [
      '3+ года в motion',
      'Портфолио с web-motion',
      'Принципы анимации',
    ],
    benefits: [
      'Проектная оплата',
      'Гибкий график',
      'Кредит в Innertalk',
    ],
  },
  {
    id: 'account-manager',
    title: 'Account Manager',
    team: 'Operations',
    location: 'Москва',
    type: 'Full-time',
    salary: '180 000 – 250 000 ₽',
    experience: '3+ года',
    short: 'Ведёте клиентов от первого созвона до сдачи. Мост между командой и бизнесом.',
    description: 'Помогаете клиентам получать максимум от сотрудничества со студией. Ведёте коммуникацию, фиксируете договорённости, следите за сроками и бюджетом.',
    responsibilities: [
      'Ведение 5-7 клиентских проектов одновременно',
      'Коммуникация на всех этапах',
      'Контроль бюджета и сроков',
      'Развитие текущих клиентов (upsell)',
    ],
    requirements: [
      '3+ года аккаунт-менеджмента в digital',
      'Отличная письменная и устная коммуникация',
      'Опыт работы с Notion / Linear',
      'Английский B1+',
    ],
    benefits: [
      'ДМС',
      'Офис в центре Москвы',
      'Квартальные бонусы',
      'Обучение переговорам',
    ],
  },
];

export type Position = (typeof positions)[number];
